<?php echo $this->headTitle('Admin Page'); ?>

<div>
    <?php $this->getNotificationHelper(); ?>
</div>

<?php
/** @var \Zend\Paginator\Paginator $paginator */
$paginator = $this->paginator;
?>
<?php if (count($paginator) > 0) : ?>
    <table class="table">
        <thead>
        <tr>
            <th>Avatar</th>
            <th>Email</th>
            <th>Message</th>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        <?php /** @var \Application\Entity\PostEntity $post */ ?>
        <?php foreach ($paginator as $post) : ?>
            <tr id="<?php echo $post->getId(); ?>">
                <td>
                    <?php
                    if (!empty($post->getAvatar())) {
                        $avatar = $this->avatarUploadPath . DIRECTORY_SEPARATOR . $post->getAvatar();
                    } else {
                        $avatar = $this->basePath('img/noavatar.png');
                    }
                    ?>
                    <img width="50px"
                         src="<?php echo $avatar; ?>"
                         alt="avatar"/>
                </td>
                <td><?php echo $post->getEmail(); ?></td>
                <td><?php echo $post->getMessage(); ?></td>
                <td>
                    <a class="confirm-delete"
                       href="<?php echo $this->url('admin/post/delete', ['id' => $post->getId()]); ?>">Delete</a>
                </td>
                <td>
                    <?php if (!$post->getIsPublic()) : ?>
                        <a class="confirm-public"
                           href="<?php echo $this->url('admin/post/public', ['id' => $post->getId()]); ?>">Public</a>
                    <?php else : ?>
                        <a class="confirm-hide"
                           href="<?php echo $this->url('admin/post/hide', ['id' => $post->getId()]); ?>">Hide</a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <div class="text-center">
        <?php echo $this->paginationControl($paginator, 'sliding', 'partial/pagination', ['route' => 'admin']); ?>
    </div>
<?php endif; ?>

<!-- Не выносил скрипты в отдельный файл просто для удобства проверки -->
<script>
    function confirmAction(message) {
        return confirm(message);
    }

    $(function () {
        $('.confirm-delete').on('click', function () {
            confirmAction("Are you sure you want to delete this post?");
        });

        $('.confirm-public').on('click', function () {
            confirmAction("Are you sure you want to publish this post?");
        });

        $('.confirm-hide').on('click', function () {
            confirmAction("Are you sure you want to hide this post?");
        });
    });
</script>